# Read data
d = read.csv("data assimilated.csv")
# 1. Do states with higher percentage of low income population have a higher percentage of uninsured
people?
# Simple linear regression
plot(d$PERCENT_POVERTY,d$PERCENT_UNINSURED_POP,xlab="Percentage of people below
poverty line ",ylab="Uninsured percentage ")
cov(d$PERCENT_POVERTY,d$PERCENT_UNINSURED_POP)
m1 = lm(PERCENT_UNINSURED_POP~PERCENT_POVERTY,data=d)
summary(m1)
# 2. Do states with higher percentage of people with less or no education have a higher percentage of
uninsured people?
# Simple linear regression
plot(d$PERCENT_LESS_HIGH,d$PERCENT_UNSINSURED_POP,xlab="Percentage of undereducated
population ",ylab="Uninsured percentage ")
cov(d$PERCENT_LESS_HIGH,d$PERCENT_UNSINSURED_POP)
m2 = lm(PERCENT_UNINSURED_POP~PERCENT_LESS_HIGH,data=d)
summary(m2)
# 3. Do states with higher unemployment rates have a higher percentage of uninsured people?
# Simple linear regression
plot(d$EST_UNEMPLOYMENT,d$PERCENT_UNINSURED_POP,xlab="Percentage of unemployed
population ",ylab="Uninsured percentage ")
cov(d$EST_UNEMPLOYMENT,d$PERCENT_UNSINSURED_POP)
m3 = lm(PERCENT_UNINSURED_POP~EST_UNEMPLOYMENT,data=d)
summary(m3)
# Main research question: Can income, education and employment be used to predict the percentage of
uninsured people in various states in the U.S.?
# Multiple linear regression
m1 = lm(PERCENT_UNINSURED_POP~PERCENT_POVERTY,data=d)
m2 = lm(PERCENT_UNINSURED_POP~PERCENT_LESS_HIGH,data=d)
m3 = lm(PERCENT_UNINSURED_POP~EST_UNEMPLOYMENT,data=d)
m4 = lm(PERCENT_UNINSURED_POP~PERCENT_POVERTY+PERCENT_LESS_HIGH,data=d)
m5 = lm(PERCENT_UNINSURED_POP~PERCENT_LESS_HIGH+EST_UNEMPLOYMENT,data=d)
m6 = lm(PERCENT_UNINSURED_POP~PERCENT_POVERTY+EST_UNEMPLOYMENT,data=d)
m7 =
lm(PERCENT_UNINSURED_POP~PERCENT_POVERTY+PERCENT_LESS_HIGH+EST_UNEMPL
OYMENT,data=d)
summary(m1)
summary(m2)
summary(m3)
summary(m4)
summary(m5)
summary(m6)
summary(m7)
anova(m1,m4)
anova(m2,m4)
anova(m2,m5)
anova(m3,m5)
anova(m1,m6)
anova(m3,m6)
anova(m4,m7)
anova(m5,m7)
anova(m6,m7)
anova(m1,m7)
anova(m2,m7)
anova(m3,m7)
# Tests for assumptions of linear regression
# generate predicted and residual values
pred=m1$fitted.values
res=m1$residuals
# Test for Independence of errors
durbinWatsonTest(m1)
# Test for Constancy of errors
plot(pred,res)
# Test for Normality of errors
qqnorm(res)
qqline(res)
shapiro.test(res)
#Test for non-linearity
plot(d$PERCENT_POVERTY,d$PERCENT_UNINSURED_POP,xlab="Percentage of people below
poverty line ",ylab="Uninsured percentage ")
plot(d$PERCENT_LESS_HIGH,d$PERCENT_UNSINSURED_POP,xlab="Percentage of undereducated
population ",ylab="Uninsured percentage ")
plot(d$EST_UNEMPLOYMENT,d$PERCENT_UNINSURED_POP,xlab="Percentage of unemployed
population ",ylab="Uninsured percentage ")
